### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by jojoe77777** [LegionPE/LegionPE-Theta-Base#11]
Line 33 of https://github.com/LegionPE/LegionPE-Theta-Base/blob/4339fd447240c37933df384a2890079f9ec592d0/resources/langs/en.json

 "donate": "%error%Please doante to use this command."

(It says doante)

**Comment by PEMapModder** [comment]
This was already fixed in recent commits. Please refer to the latest commits in issues.

**Comment by jojoe77777** [comment]
Uhhhhhhh ok... I REALLY thought I was looking at the latest code.
